
resolver: lts-18.18
packages:
    - .
extra-deps:
    - text-format-0.3.2
    - Diff-0.3.4
    - location:
      git: https://github.com/ucsd-progsys/liquidhaskell
      commit: b8dc0c2bdff8e6ea9ec4a9fc2439e89fdcd73b69
    - location: 
      git: https://github.com/liquidhaskell/liquid-base
      commit: 79e2bee57ef6e34e69a80cd361bc8edde80da34a
    - liquid-prelude-0.8.10.2 
    - location: 
      git: https://github.com/liquidhaskell/liquid-containers
      commit: 845942a8fdca5ab785c2e0e5202e5beaf94bc327
    - liquid-ghc-prim-0.6.1
    - location: 
      git: https://github.com/ucsd-progsys/liquid-fixpoint
      commit: d6c95d1d535125f99f382fa503d012d008b0d480
    - location:
      git: https://github.com/zgrannan/rest
      commit: 1cadb23edfbc393245ae964315b07f5c8581ea9f

allow-newer: true
