coqc -Q . SystemRF BasicDefinitions.v
coqc -Q . SystemRF Names.v
coqc -Q . SystemRF Strengthenings.v
coqc -Q . SystemRF LocalClosure.v
coqc -Q . SystemRF Semantics.v
coqc -Q . SystemRF SystemFWellFormedness.v
coqc -Q . SystemRF SystemFTyping.v
coqc -Q . SystemRF PrimitivesFTyping.v
coqc -Q . SystemRF BasicPropsSubstitution.v
coqc -Q . SystemRF BasicPropsEnvironments.v
coqc -Q . SystemRF BasicPropsWellFormedness.v
coqc -Q . SystemRF SystemFLemmasWellFormedness.v
coqc -Q . SystemRF SystemFLemmasWeaken.v
coqc -Q . SystemRF SystemFLemmasSubstitution.v
coqc -Q . SystemRF SystemFSoundness.v
